### ISSUE TITLE
注音符號的華語詞

### ISSUE THREAD

**Issue by a8568730** [sih4sing5hong5/su5lui3-hun1kip4#40]
ID：620 
編號：08《彰化縣國民小學鄉土語言臺語其他教材第八冊》
內文：
```
ㄐ    ㄑ   ngi  ㄒ
tsi tshi ngi1 si
```

**Comment by sih4sing5hong5** [comment]
https://github.com/sih4sing5hong5/su5lui3-hun1kip4-hok8bu7/issues/24
有矣
